use_frameworks!

target 'HaiGCDTimerPod_Example' do
  pod 'HaiGCDTimerPod', :path => '../'

  target 'HaiGCDTimerPod_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
